usethis::use_git_config(user.name = "johan-rosa", user.email = "johan.rosaperez@gmail.com")
usethis::create_github_token()
usethis::edit_r_environ()
gitcreds::gitcreds_set()
#credentials::set_github_pat()
